
import "./globals.css";
// import LgNavbar from "@/components/Navbar/LgNavbar";
import MobileMenu from "../components/Navbar/MobileMenu";
import Footer from "@/components/Footer";
import { RegularFont } from "../utils/fonts";
import LgNavbar from "../components/Navbar/LgNavbar";
import Navbar from '.././components/Navbar/Navbar'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={RegularFont.className}>


        <Navbar />

        <div className="z-10 overflow-hidden">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
